### ISSUE TITLE
Загружено слишком мало файлов

### ISSUE THREAD

**Issue by antonror** [Viktoriia13/Start1#1]
**Привет** я оценил твой первый _репозиторий_. Однако в нём слишком мало файлов. Добавь ещё

`the_piece_of_code`

**Comment by Viktoriia13** [comment]
Иди прогуляйся, это **# МОЙ** репозиторий и то, сколько в нем файлов - моё личное дело!

**Comment by antonror** [comment]
Хорошо, я вернусь позже

**Comment by Viktoriia13** [comment]
Issue закрыта

**Comment by Viktoriia13** [comment]
Issue закрыта
